image: omos/argon2-gpu:zesty

before_script:
    - git submodule update --init

cache:
    paths:
        - "build/"

build:
    only:
        - ci
    stage: build
    script:
        - mkdir -p build
        - cd build
        - cmake ..
        - make

#test:
    #only:
        #- ci
    #stage: test
    #script:
        #- cd build
        #- CTEST_OUTPUT_ON_FAILURE=1 make test
